-- MySQL Script generated by MySQL Workbench
-- 05/26/16 19:04:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ISC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ISC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISC2_0` DEFAULT CHARACTER SET utf8 ;
USE `ISC2_0` ;

-- -----------------------------------------------------
-- Table `ISC`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISC2_0`.`product_type` (
  `id_product_type` INT NOT NULL AUTO_INCREMENT,
  `product_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product_type`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_cost` VARCHAR(45) NOT NULL,
  `product_amount` VARCHAR(45) NOT NULL,
  `product_date_storage` DATE NOT NULL,
  `id_product_type` INT NOT NULL,
  PRIMARY KEY (`id_product`, `id_product_type`),
  INDEX `fk_products_product_type_idx` (`id_product_type` ASC),
  CONSTRAINT `fk_products_product_type`
  FOREIGN KEY (`id_product_type`)
  REFERENCES ISC2_0.`product_type` (`id_product_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_firm` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `address_user` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id_user`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`phone_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`phone_type` (
  `id_phone_type` INT NOT NULL AUTO_INCREMENT,
  `type_phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_phone_type`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`user_phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`user_phones` (
  `id_phone` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `id_phone_type` INT NOT NULL,
  PRIMARY KEY (`id_phone`, `id_user`, `id_phone_type`),
  INDEX `fk_clients_phones_clients1_idx` (`id_user` ASC),
  INDEX `fk_user_phones_phone_type1_idx` (`id_phone_type` ASC),
  CONSTRAINT `fk_clients_phones_clients1`
  FOREIGN KEY (`id_user`)
  REFERENCES ISC2_0.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_phones_phone_type1`
  FOREIGN KEY (`id_phone_type`)
  REFERENCES ISC2_0.`phone_type` (`id_phone_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order_status` (
  `id_order_status` INT NOT NULL AUTO_INCREMENT,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_order_status`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`transport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`transport` (
  `id_transport` INT NOT NULL AUTO_INCREMENT,
  `name_transport` VARCHAR(45) NOT NULL,
  `min_tonnage` DOUBLE NULL,
  `max_tonnage` DOUBLE NULL,
  PRIMARY KEY (`id_transport`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `date_delivery` DATE NOT NULL,
  `time_delivery` VARCHAR(45) NOT NULL,
  `date_order` DATE NOT NULL,
  `price_order` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  `id_order_status` INT NOT NULL,
  `transport_id_transport` INT NOT NULL,
  PRIMARY KEY (`id_order`, `id_user`, `id_order_status`, `transport_id_transport`),
  INDEX `fk_orders_clients1_idx` (`id_user` ASC),
  INDEX `fk_orders_order_status1_idx` (`id_order_status` ASC),
  INDEX `fk_order_transport1_idx` (`transport_id_transport` ASC),
  CONSTRAINT `fk_orders_clients1`
  FOREIGN KEY (`id_user`)
  REFERENCES ISC2_0.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_status1`
  FOREIGN KEY (`id_order_status`)
  REFERENCES ISC2_0.`order_status` (`id_order_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_transport1`
  FOREIGN KEY (`transport_id_transport`)
  REFERENCES ISC2_0.`transport` (`id_transport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`spot_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`spot_type` (
  `id_spot_type` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_spot_type`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order_spot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order_spot` (
  `id_order_spot` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `spot_type` VARCHAR(45) NULL,
  `spot_type_id_spot_type` INT NOT NULL,
  `order_id_order` INT NOT NULL,
  `order_id_user` INT NOT NULL,
  `order_id_order_status` INT NOT NULL,
  `order_transport_id_transport` INT NOT NULL,
  PRIMARY KEY (`id_order_spot`, `spot_type_id_spot_type`, `order_id_order`, `order_id_user`, `order_id_order_status`, `order_transport_id_transport`),
  INDEX `fk_order_spot_spot_type1_idx` (`spot_type_id_spot_type` ASC),
  INDEX `fk_order_spot_order1_idx` (`order_id_order` ASC, `order_id_user` ASC, `order_id_order_status` ASC, `order_transport_id_transport` ASC),
  CONSTRAINT `fk_order_spot_spot_type1`
  FOREIGN KEY (`spot_type_id_spot_type`)
  REFERENCES ISC2_0.`spot_type` (`id_spot_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_spot_order1`
  FOREIGN KEY (`order_id_order` , `order_id_user` , `order_id_order_status` , `order_transport_id_transport`)
  REFERENCES ISC2_0.`order` (`id_order` , `id_user` , `id_order_status` , `transport_id_transport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`product_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`product_order` (
  `id_product_order` INT NOT NULL AUTO_INCREMENT,
  `amount_product` VARCHAR(45) NOT NULL,
  `price_amount` VARCHAR(45) NOT NULL,
  `id_product` INT NOT NULL,
  `id_product_type` INT NOT NULL,
  `order_spot_id_order_spot` INT NOT NULL,
  `order_spot_spot_type_id_spot_type` INT NOT NULL,
  `order_spot_order_id_order` INT NOT NULL,
  `order_spot_order_id_user` INT NOT NULL,
  `order_spot_order_id_order_status` INT NOT NULL,
  `order_spot_order_transport_id_transport` INT NOT NULL,
  PRIMARY KEY (`id_product_order`, `id_product`, `id_product_type`, `order_spot_id_order_spot`, `order_spot_spot_type_id_spot_type`, `order_spot_order_id_order`, `order_spot_order_id_user`, `order_spot_order_id_order_status`, `order_spot_order_transport_id_transport`),
  INDEX `fk_product_order_product1_idx` (`id_product` ASC, `id_product_type` ASC),
  INDEX `fk_product_order_order_spot1_idx` (`order_spot_id_order_spot` ASC, `order_spot_spot_type_id_spot_type` ASC, `order_spot_order_id_order` ASC, `order_spot_order_id_user` ASC, `order_spot_order_id_order_status` ASC, `order_spot_order_transport_id_transport` ASC),
  CONSTRAINT `fk_product_order_product1`
  FOREIGN KEY (`id_product` , `id_product_type`)
  REFERENCES ISC2_0.`product` (`id_product` , `id_product_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_order_order_spot1`
  FOREIGN KEY (`order_spot_id_order_spot` , `order_spot_spot_type_id_spot_type` , `order_spot_order_id_order` , `order_spot_order_id_user` , `order_spot_order_id_order_status` , `order_spot_order_transport_id_transport`)
  REFERENCES ISC2_0.`order_spot` (`id_order_spot` , `spot_type_id_spot_type` , `order_id_order` , `order_id_user` , `order_id_order_status` , `order_transport_id_transport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`product_type` (
  `id_product_type` INT NOT NULL AUTO_INCREMENT,
  `product_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product_type`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`user_role` (
  `id_user_role` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(45) NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_user_role`, `user_id_user`),
  INDEX `fk_user_role_clients1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_user_role_clients1`
  FOREIGN KEY (`user_id_user`)
  REFERENCES ISC2_0.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order_route` (
  `id_order_route` INT NOT NULL AUTO_INCREMENT,
  `start_route` VARCHAR(45) NOT NULL,
  `end_route` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_order_route`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order_route_spot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order_route_spot` (
  `id_order_route_spot` INT NOT NULL AUTO_INCREMENT,
  `name_spot` VARCHAR(45) NOT NULL,
  `road_path` VARCHAR(45) NULL,
  `order_route_id_order_route` INT NOT NULL,
  PRIMARY KEY (`id_order_route_spot`, `order_route_id_order_route`),
  INDEX `fk_order_route_spot_order_route1_idx` (`order_route_id_order_route` ASC),
  CONSTRAINT `fk_order_route_spot_order_route1`
  FOREIGN KEY (`order_route_id_order_route`)
  REFERENCES ISC2_0.`order_route` (`id_order_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ISC`.`order_route_has_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ISC2_0.`order_route_has_order` (
  `order_route_id_order_route` INT NOT NULL,
  `order_id_order` INT NOT NULL,
  `order_id_user` INT NOT NULL,
  `order_id_order_status` INT NOT NULL,
  `order_transport_id_transport` INT NOT NULL,
  PRIMARY KEY (`order_route_id_order_route`, `order_id_order`, `order_id_user`, `order_id_order_status`, `order_transport_id_transport`),
  INDEX `fk_order_route_has_order_order1_idx` (`order_id_order` ASC, `order_id_user` ASC, `order_id_order_status` ASC, `order_transport_id_transport` ASC),
  INDEX `fk_order_route_has_order_order_route1_idx` (`order_route_id_order_route` ASC),
  CONSTRAINT `fk_order_route_has_order_order_route1`
  FOREIGN KEY (`order_route_id_order_route`)
  REFERENCES ISC2_0.`order_route` (`id_order_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_route_has_order_order1`
  FOREIGN KEY (`order_id_order` , `order_id_user` , `order_id_order_status` , `order_transport_id_transport`)
  REFERENCES ISC2_0.`order` (`id_order` , `id_user` , `id_order_status` , `transport_id_transport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
